Fixed #14851 -- Swapped an argument order to fix compatibility with Python<2.6. Thanks for report and patch, mk.

git-svn-id: http://code.djangoproject.com/svn/django/trunk@14845 bcc190cf-cafb-0310-a4f2-bffc1f526a37
